iamstevendao/vue-tel-input

- README.md
- src/vue-tel-input.vue
This is addressing this issue
https://github.com/EducationLink/vue-tel-input/issues/58
This gives the user more control over autocomplete to tweak according to preference. Defaults to "on" as is the case with native input.
>  Enables autocomplete attribute

- src/vue-tel-input.vue
The 'click-outside' Vue directive is not working when using it inside a web component.
In order to mantain the web components encapsulation principle, when the ‘click’ event is triggered from an element that is inside of the “#shadow-root”, the browser retargets the event to the host element of the shadow dom.
For example, clicking the element `<p data-v-9b69508e=""> I'm a web component</p>,` the `e.target` code returns `<my-web-component>` as clicked element:
So the problem is the `e.target` code that is retargeted to the host element. 
To solve this, we can use instead the `e.path[0]` code to get the clicked element to add support to use it inside web components.
> Web Components Support

- src/vue-tel-input.vue
This Pull request includes `open` and `close` event emits, in order to inform the parent component when the the dropdown is opened.
Added a watcher for the `open` state, in order to emit open or close event, when `open` changes to `true` or `false` accordingly.
> Add open and close event emits

- README.md
- src/vue-tel-input.vue
According to this [issue](https://github.com/EducationLink/vue-tel-input/issues/90) the `id` attribute should be mandatory for every input element
> [ADD] id as a property

- src/vue-tel-input.vue
Fixes https://github.com/EducationLink/vue-tel-input/issues/108
I suppose adding `e.preventDeafult()` shouldn't affect any other things. Let me know if it does.
> Added preventDefault to prevent window scrolling

- src/App.vue
- src/components/vue-tel-input.vue
- src/utils.js
Has been added new attribute `custom-validate` which takes the value as a regular expression. 
For example. Limit to entering the numbers only.
`<vue-tel-input :custom-validate="/^[0-9]*$/" />`
It helps to solve the issue https://github.com/EducationLink/vue-tel-input/issues/27
> created the 'сustom-validate' prop to validate with regex

- src/components/vue-tel-input.vue
`this.choose` upon `e.keyCode === 13` was missing `true` option.
> fix #179: pressing Enter in country selector does not re-validate phone number

- docs/documentation/installation.md
- package.json
- src/components/vue-tel-input.vue
- src/utils.js
- vue.config.js
This PR also extracts the css so you can import it, if you are using the component directly (and not as a plugin).
Also we added the ability to change the input property "type" via a property, if needed.
> fix: change country flag on click, even if international mode is NOT used

- docs/documentation/v3.md
- src/components/vue-tel-input.test.js
- src/components/vue-tel-input.vue
Have allowed defaultCountry to accept both string and number, which make it possible to choose default country by dialCode - based on @iamstevendao comment https://github.com/EducationLink/vue-tel-input/pull/171#issuecomment-591115661
> Allow defaultCountry prop to accept both iso2 and dialCode

- README.md
Found out today that it's not that easy to lazy load component (as it's one of the biggest in the app I'm building). 
Added a section to the README explaining the right way of doing so.
It seems like I need to add it to vuepress as well. Could tell me how and where I should do so?
> docs(README): describe lazy loading technique

- src/components/vue-tel-input.vue
- src/utils.js
This fixes issue where, when `inputOptions.showDialCode` is set to true, flag isn't updated until full number is available. Fixes #283
Purposefully duplicated line to avoid refactoring `choose()` method, risking introducing regression issues
Also added missing documentation for inputOptions.showDialCode
> Update selected country when showDialCode is set

- README.md
It's not valid syntax to have a `<style>` tag within the `<script>`
tag in a `.vue` file. Instead, move this example to its own top-level
attribute.
Notably, this matches the example in `docs/documentation/installation.md`
> Doc fix: move style tag *outside* of script tag

- src/assets/component.css
- src/components/vue-tel-input.vue
- src/utils.js
Changing dropdown size only using css was not easily achievable since `vti__dropdown-list` was placed inside `vti__dropdown` making `width: 100%` not working properly.
I figured out adding a "dropdown width" option would be a much easier and cleaner solution.
Is that okay with you?
> Add the ability to change dropdown width

- src/assets/component.css
- src/components/vue-tel-input.vue
Switzerland flag width is 15px where every other flags are 20px this causes flags and texts misalignment.
This PR addresses the issue by adding a wrapper around the flag fixing the width to 30px (20px for the flag, 10px for both margins).
> Added flag wrapper to fix width inconsistencies

- src/components/vue-tel-input.vue
When search query do not match with the name or dial code of any countries, it throws an error-
`TypeError: Cannot read properties of undefined (reading 'name’)` 
This error is coming from the placeholder of the search input which is binded with `sortedCountries[0].name`. 
Added a check on `sortedCountires.length` to catch this error.
> TypeError in dropdown search box

- src/components/vue-tel-input.vue
Found this issue in both Safari and Firefox, When the cursor is focused on search input box, the dropdown gets closed. This is due to the event propagation happening from the input box, which ultimately calls the `clickedOutside` directive.
> event propagation in dropdown searchbox - Firefox & Safari

- .browserslistrc.legacy
- .browserslistrc.modern
- .gitignore
- babel.config.js
- package.json
The previous behavior that set browserslit config from babel.config.js
did not work on files not provided in repo (e.g. webpack bookstrap).
The new behavior copy the appropriate .browserslistrc file to the repo
before build.
Fixes IE 11 compatibility which was broken since https://github.com/iamstevendao/vue-tel-input/pull/264, release in `v5.4.0`.
see dist diff (`npm diff dist/vue-tel-input.umd.js`) :
```diff
diff --git a/dist/vue-tel-input.umd.js b/dist/vue-tel-input.umd.js
index v5.10.0..v5.10.0 100644
--- a/dist/vue-tel-input.umd.js
+++ b/dist/vue-tel-input.umd.js
@@ -8,7 +8,7 @@
else
root["vue-tel-input"] = factory();
})((typeof self !== 'undefined' ? self : this), function() {
-return /******/ (() => { // webpackBootstrap
+return /******/ (function() { // webpackBootstrap
/******/ …
```
> fix(build): use browserslist config on all chunks

- package.json
reason:
doesn't get the right country.
the fix of this library was introduced on this commit: 
- https://gitlab.com/catamphetamine/libphonenumber-js/-/commit/6743a40c17a685698f656c634dfb9ab1124f47c9
Before:
https://user-images.githubusercontent.com/30967304/184786576-8ab32cb1-5e35-4685-a7c4-586b841f5eb7.mp4
After:
https://user-images.githubusercontent.com/30967304/184788070-4f1c80be-2eb4-447e-af14-bfa960e5567a.mov
> updating dependecy libphonenumber-js from ^1.9.6 to ^1.10.12

- src/components/vue-tel-input.vue
When you input special chars to showSearchBox, it throws an error as you can see in screenshot.
there is also an issue about this error: #402 
With this pr, special characters are ignored and countries are listed according to the entered letter or number. I didnt use `\W` or `[a-z0-9]` regex because it won't work for non english languages like chinese, arabic, turkish etc.
> fix: special chars in showSearchBox

- src/assets/all-countries.js
Change DR Congo's extended name to its French notation, which is the official language.
> countries: update DR Congo's extended name

- tsconfig.json
Tests files should not be included into building types.
> fix: exclude tests from TSConfig

- src/components/vue-tel-input.vue
Fix for #462 (and potentially #452)
Issue in version >9 where if prop `mode` set to `auto` would be unable to change/edit the phone number input after the phone number has been formatted due to a bug in a compute value of `parsedMode` that leads to an endless changing of value of the `phoneObject` which would then change the `parsedMode` return value, which would then change the value of `phoneObject`, etc etc.
The main culprit of this seems to be of how an `if` condition is being handled making `parsedMode` return the inappropriate value when `result?.format(toUpperCase(parsedMode.value))` is being executed.
> fix: prevent infinite loop in parsedMode calculation

- src/components/vue-tel-input.vue
**Issue**
Country search doesn't work for input containing capital letters (INDIA, inDIa).
**Steps to reproduce**
1. Enable dropdown options with `showSearchBox: true`
2. Type INDIA and check dropdown options
3. Type inDIa and check dropdown options
**Proposed solution**
Convert user input to lowercase before filtering the countries list
**After the fix**
> Fix: Country search should not be case sensitive

- src/components/vue-tel-input.vue
Fix this error:
When we focus on the input flag, we press an alphanumeric character, the error appears.
> fix: Error after tabbing to the country field

- README.md
Fix links from `vue-tel-input.iamstevendao.com` to `iamstevendao.com/vue-tel-input`
> :memo: Update readme links

- vite.config.ts
libphonenumber-js was made a peer dependency but the build of this component ignores the user's installed version. This fix makes the package properly use the user's installed version of libphonenumber-js
> make libphonenumber-js external
