iamstevendao/vue-tel-input

src/vue-tel-input.vue
Added a created-hook so the component can be loaded with a phone number.
=> Add created-hook

package.json
Added repository and homepage fields to package.json.
=> Fixes #30 Add repository field to package.json

src/vue-tel-input.vue
added the capability to pass the prop required to component in order to use html5 required attribute on form submission
=> added props to use html5 required attribute

README.md, src/vue-tel-input.vue
Ability to add a custom class to the input using props
=> Custom input class

README.md, src/vue-tel-input.vue
=> Added ability to display country code

README.md, src/vue-tel-input.vue
Add option to have custom classes for the parent
=> Mariusgen patch wrapper class

README.md
1. Add readme typescript docs.
=> Typescript support

src/vue-tel-input.vue
=> Closes #87

README.md, src/vue-tel-input.vue
New feature to be able to modify the dropdown and input tabindex using the `dropdownOptions` and `inputOptions` objects.
=> Usability improvements

src/vue-tel-input.vue
Feature: customizing dropdown arrows #113
=> Add "arrow-icon" slot

src/vue-tel-input.vue
This allows easier translations, or modifying countries list.
related to #44
PR only includes changes in source files.
=> make allCountries a property

README.md, src/components/vue-tel-input.vue
Add `focus` event, as requested on #149
=> Add `focus` event. Fix #149

src/components/vue-tel-input.vue
Hi, there is an adjust dropdown position feature (below or above the input, if there is not enough space below).
=> Feature: Change the dropdown position if there is not enough space below

package-lock.json, src/components/vue-tel-input.vue
- If enabledFlags is explicitly set to false, don't fetch the sprite.css. This will reduce the bundle size straight 114KB down.
- If set to true (or by default), css file will be bundled separately and imported dynamically.
@iamstevendao
=> code splitting : fetch css file only if enabledFlags is set to true

package.json
Better and wider phone support. This library should be updated frequently to ensure the best phone validation coverage.
=> Update awesome-phonenumber library to latest version.

src/components/vue-tel-input.vue
Hi, it is the PR for #231 
Add invalid value to phone number object if country is not exists in filtered list
=> Add invalid validation if country not exists in list

docs/documentation/slots.md, src/components/vue-tel-input.vue
I am using the [Bulma](https://bulma.io/) UI framework, and would like to be able to provide a sibling element to the `input`, in order to display an icon to represent whether or not the input is valid.
This merge request adds a slot, such that a sibling element to the `input` may be added.
=> Add Icon Slot

src/assets/component.css, src/components/vue-tel-input.vue, src/utils.js
Search functionality can be disabled by by `isSearchable` flag. By default it is set to true.
=> Added search functionality.

src/components/vue-tel-input.vue
Our worked just passed accessibility audit. Figured I'd push these up to the `next` branch as well since we're developing in Vue 3.
=> Same accessibility updates as done to master branch

src/components/vue-tel-input.vue
You probably forgot to change value to modelValue in watchers while migrating to vue 3 :) have a nice day!
=> fix (component): rename value to modelValue

package-lock.json, package.json
=> add-peer-dependencies

src/assets/all-countries.js
This PR corrects of DR Congo country name, to its official French name.
=> fix(countries): update CD country name

docs/guide/installation.md
I got this error when trying to import the css from the docs.
=> Wrong import path of css file

src/components/vue-tel-input.test.js, src/components/vue-tel-input.vue
Hi, I just want to fix [issue](https://github.com/iamstevendao/vue-tel-input/issues/485). I don't know if I could update the legacy code from `legacy` branch but I try to create MR here. Could you please go over this MR @iamstevendao? Thanks
=> fix: allows to search insensitive country'name

package-lock.json, package.json, src/components/vue-tel-input.vue
Regarding this issue (https://github.com/iamstevendao/vue-tel-input/issues/483), I updated the Vue version to the latest version (3.5.4).
If you will need anything else just let me know!!!
=> feat: Update Vue version from 3.4.21 to 3.5.4
